// Catálogo de ejercicios disponibles para las sesiones de pausas activas.
import type { Ejercicio } from './types';

export const ejercicios: Ejercicio[] = [
  { nombre: 'Estiramiento de cuello', descripcion: 'Inclina la cabeza suavemente de lado a lado.', duracion: 30, mediaUrl: '/exercises/estiramiento-cuello.png' },
  { nombre: 'Rotación de hombros', descripcion: 'Gira los hombros hacia adelante y luego hacia atrás.', duracion: 30, mediaUrl: '/exercises/rotacion-hombros.png' },
  { nombre: 'Estiramiento de brazos', descripcion: 'Extiende un brazo por encima de la cabeza y dóblalo, usando el otro para un estiramiento suave.', duracion: 45, mediaUrl: '/exercises/estiramiento-brazos.png' },
  { nombre: 'Estiramiento de muñecas', descripcion: 'Extiende un brazo y flexiona la muñeca hacia arriba y abajo.', duracion: 30, mediaUrl: '/exercises/estiramiento-munecas.png' },
  { nombre: 'Giro de torso', descripcion: 'Sentado, gira el torso suavemente a cada lado.', duracion: 45, mediaUrl: '/exercises/giro-torso.png' },
  { nombre: 'Levantamiento de rodillas', descripcion: 'De pie, levanta las rodillas alternadamente hacia el pecho.', duracion: 60, mediaUrl: '/exercises/levantamiento-rodillas.png' },
  { nombre: 'Estiramiento de isquiotibiales', descripcion: 'Sentado, extiende una pierna y trata de tocar la punta del pie.', duracion: 45, mediaUrl: '/exercises/estiramiento-isquiotibiales.png' },
  { nombre: 'Círculos de tobillo', descripcion: 'Levanta un pie y haz círculos con el tobillo en ambas direcciones.', duracion: 30, mediaUrl: '/exercises/circulos-tobillo.png' },
  { nombre: 'Respiración profunda', descripcion: 'Inhala profundamente por la nariz y exhala lentamente por la boca.', duracion: 60, mediaUrl: '/exercises/respiracion-profunda.png' },
  { nombre: 'Mirada lejana', descripcion: 'Enfoca la vista en un objeto lejano por 20 segundos para relajar los ojos.', duracion: 30, mediaUrl: '/exercises/mirada-lejana.png' },
  { nombre: 'Estiramiento de espalda', descripcion: 'De pie, entrelaza los dedos y estira los brazos hacia el techo.', duracion: 45, mediaUrl: '/exercises/estiramiento-espalda.png' },
  { nombre: 'Sentadillas en silla', descripcion: 'Simula sentarte y levantarte de una silla sin usar las manos.', duracion: 60, mediaUrl: '/exercises/sentadillas-silla.png' },
  { nombre: 'Flexiones en la pared', descripcion: 'Apoya las manos en la pared y haz flexiones de brazos.', duracion: 60, mediaUrl: '/exercises/flexiones-pared.png' },
  { nombre: 'Estiramiento de pantorrillas', descripcion: 'Apóyate en una pared y da un paso atrás, manteniendo la pierna recta.', duracion: 45, mediaUrl: '/exercises/estiramiento-pantorrillas.png' },
  { nombre: 'Marcha en el sitio', descripcion: 'Camina en tu lugar levantando bien las rodillas.', duracion: 60, mediaUrl: '/exercises/marcha-sitio.png' },
  { nombre: 'Estiramiento de tríceps', descripcion: 'Pasa un brazo por detrás de la cabeza y tira suavemente del codo con la otra mano.', duracion: 30, mediaUrl: '/exercises/estiramiento-triceps.png' },
  { nombre: 'Encogimiento de hombros', descripcion: 'Levanta los hombros hacia las orejas y luego relájalos.', duracion: 30, mediaUrl: '/exercises/encogimiento-hombros.png' },
  { nombre: 'Estiramiento de gato-vaca', descripcion: 'A cuatro patas, arquea y redondea la espalda lentamente.', duracion: 60, mediaUrl: '/exercises/gato-vaca.png' },
  { nombre: 'Abrazo de oso', descripcion: 'Cruza los brazos sobre el pecho y abrázate fuerte, luego cambia de brazo.', duracion: 30, mediaUrl: '/exercises/abrazo-oso.png' },
  { nombre: 'Estiramiento de dedos', descripcion: 'Abre y cierra las manos con fuerza varias veces.', duracion: 30, mediaUrl: '/exercises/estiramiento-dedos.png' },
  { nombre: 'Inclinación pélvica', descripcion: 'Sentado o de pie, contrae los abdominales para aplanar la espalda baja.', duracion: 45, mediaUrl: '/exercises/inclinacion-pelvica.png' },
  { nombre: 'Estiramiento lateral', descripcion: 'De pie, levanta un brazo y estírate hacia el lado contrario.', duracion: 45, mediaUrl: '/exercises/estiramiento-lateral.png' },
  { nombre: 'Rotación de cadera', descripcion: 'De pie, haz círculos con la cadera en ambas direcciones.', duracion: 45, mediaUrl: '/exercises/rotacion-cadera.png' },
  { nombre: 'Palmas oculares', descripcion: 'Frota las palmas para calentarlas y colócalas suavemente sobre los ojos cerrados.', duracion: 60, mediaUrl: '/exercises/palmas-oculares.png' },
  { nombre: 'Estiramiento de cuádriceps', descripcion: 'De pie, sujeta un tobillo y llévalo hacia los glúteos.', duracion: 45, mediaUrl: '/exercises/estiramiento-cuadriceps.png' },
  { nombre: 'Sonrisa y relajación facial', descripcion: 'Sonríe ampliamente y luego relaja todos los músculos de la cara.', duracion: 30, mediaUrl: '/exercises/sonrisa-facial.png' },
  { nombre: 'Postura del árbol (simplificada)', descripcion: 'De pie, apoya la planta de un pie en el interior del tobillo contrario.', duracion: 60, mediaUrl: '/exercises/postura-arbol.png' },
  { nombre: 'Elevación de talones', descripcion: 'De pie, ponte de puntillas y baja lentamente.', duracion: 45, mediaUrl: '/exercises/elevacion-talones.png' },
  { nombre: 'Estiramiento del flexor de la cadera', descripcion: 'Arrodíllate y da un paso adelante, inclinándote sobre la pierna delantera.', duracion: 60, mediaUrl: '/exercises/flexor-cadera.png' },
  { nombre: 'Meditación de un minuto', descripcion: 'Cierra los ojos, concéntrate en tu respiración y despeja tu mente.', duracion: 60, mediaUrl: '/exercises/meditacion.png' },
];
